services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: eid-sqlserver
    environment:
      SA_PASSWORD: ${SQLSERVER_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  oracle:
    image: gvenzl/oracle-free:23-slim
    container_name: eid-oracle
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data: